title: Asher Hatch
subtitle: Game Dev Portfolio
description: >-
  Portfolio site for Asher Hatch.

author: Asher Hatch
email: asher1223mp@gmail.com
avatar: assets/images/avatar.jpg

url: "https://asherhatch.net"
baseurl: ""

# Prologue theme (GitHub Pages compatible)
remote_theme: chrisbobbe/jekyll-theme-prologue
plugins:
  - jekyll-remote-theme

collections: [sections]

# Social links (full URLs)
linkedin_url: https://www.linkedin.com/in/asher-hatch-367013304/
github_url: https://github.com/Floognoodle
